name: build wine on macOS
on:
  push:
    branches: [ build_wine_on_macOS-latest,master ]
  pull_request:
    branches: [ build_wine_on_macOS-latest,master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: echo
        run: echo $GITHUB_WORKSPACE
      # - name: tree
      #   run: |
      #     # brew install tree
      #     # tree $GITHUB_WORKSPACE
      #     ls $GITHUB_WORKSPACE
      - name: mkdir
        run: mkdir $GITHUB_WORKSPACE/build
      - name: cd
        run: cd $GITHUB_WORKSPACE/build
      - name: configure
        run: ../configure --enable-win64

      # Runs a set of commands using the runners shell
      - name: build
        run: make -j2
